[entity_types]
CREDIT_CARD = "HIGH"
CRYPTO = "HIGH"
DATE_TIME = "LOW"
EMAIL_ADDRESS = "MEDIUM"
IBAN_CODE = "HIGH"
IP_ADDRESS = "MEDIUM"
NRP = "MEDIUM"
LOCATION = "LOW"
PERSON = "MEDIUM"
PHONE_NUMBER = "MEDIUM"
MEDICAL_LICENSE = "HIGH"
URL = "LOW"
US_BANK_NUMBER = "HIGH"
US_DRIVER_LICENSE = "HIGH"
US_ITIN = "HIGH"
US_PASSPORT = "HIGH"
US_SSN = "HIGH"
UK_NHS = "HIGH"
UK_NINO = "HIGH"
ES_NIF = "HIGH"
ES_NIE = "HIGH"
IT_FISCAL_CODE = "HIGH"
IT_DRIVER_LICENSE = "HIGH"
IT_VAT_CODE = "HIGH"
IT_PASSPORT = "HIGH"
IT_IDENTITY_CARD = "HIGH"
PL_PESEL = "HIGH"
SG_NRIC_FIN = "HIGH"
SG_UEN = "HIGH"
AU_ABN = "HIGH"
AU_ACN = "HIGH"
AU_TFN = "HIGH"
AU_MEDICARE = "HIGH"
IN_PAN = "HIGH"
IN_AADHAAR = "HIGH"
IN_VEHICLE_REGISTRATION = "MEDIUM"
IN_VOTER = "HIGH"
IN_PASSPORT = "HIGH"
IN_GSTIN = "HIGH"
FI_PERSONAL_IDENTITY_CODE = "HIGH"
KR_RRN = "HIGH"
KR_PASSPORT = "HIGH"
TH_TNIN = "HIGH"
